In [1]:
import numpy as np
import torch

In [2]:
# Training data
# [Temp, Rainfall, Humidity]
inputs = np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]],dtype='float32')
# [Apples, Oranges]
targets = np.array([[56,70],[81,101],[119,133],[22,37],[103,119]], dtype='float32')

In [3]:
# Weights and biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-1.5169, -1.3005, -0.6126],
        [-0.0496, -0.7912,  0.6810]], requires_grad=True)
tensor([ 1.4124, -0.1572], requires_grad=True)


In [4]:
def model(x):
  return torch.matmul(x,torch.transpose(w,0,1)) + b

In [5]:
preds = model(torch.from_numpy(inputs))
print(preds)

tensor([[-222.7975,  -27.5020],
        [-290.2776,  -30.7078],
        [-340.3584,  -70.9888],
        [-231.8980,  -14.0386],
        [-270.9868,  -31.8598]], grad_fn=<AddBackward0>)


In [6]:
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [7]:
def mse(t1, t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [8]:
loss = mse(preds,torch.from_numpy(targets))
print(loss)

tensor(72474.4219, grad_fn=<DivBackward0>)


In [9]:
# Compute gradients
loss.backward()

In [10]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-1.5169, -1.3005, -0.6126],
        [-0.0496, -0.7912,  0.6810]], requires_grad=True)
tensor([[-29161.0684, -31945.2500, -19593.2305],
        [-10493.0684, -12426.9229,  -7380.3691]])


In [11]:
# Gradients for bias values
print(b)
print(b.grad)

tensor([ 1.4124, -0.1572], requires_grad=True)
tensor([-347.4637, -127.0194])


In [12]:
# ADJUST WEIGHTS AND BIASES USING GRADIENT DESCENT
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [13]:
print(w)
print(b)

tensor([[-1.2253, -0.9811, -0.4167],
        [ 0.0553, -0.6669,  0.7548]], requires_grad=True)
tensor([ 1.4159, -0.1560], requires_grad=True)


In [14]:
# Train for multiple epochs
for i in range(0,3000):
  preds = model(torch.from_numpy(inputs))
  loss =  mse(preds,torch.from_numpy(targets))
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [15]:
new_preds = model(torch.from_numpy(inputs))

In [16]:
new_loss = mse(new_preds,torch.from_numpy(targets))

In [17]:
print(new_loss)

tensor(0.5594, grad_fn=<DivBackward0>)


In [18]:
print(new_preds)

tensor([[ 57.4122,  70.2675],
        [ 81.9899, 100.8126],
        [118.7939, 132.7007],
        [ 21.0905,  36.9452],
        [101.8192, 119.3953]], grad_fn=<AddBackward0>)


In [19]:
print(w)
print(b)

tensor([[-0.4091,  0.8518,  0.6692],
        [-0.3050,  0.7878,  0.9282]], requires_grad=True)
tensor([ 1.4282, -0.1584], requires_grad=True)
