In [1]:
!pip3 install torch torchvision torchaudio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch

In [3]:
t1 = torch.tensor(4.)

In [4]:
t1

tensor(4.)

In [5]:
t2 = torch.tensor([[5.,6],[7,8],[9,10]])

In [6]:
t2

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
t3 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [8]:
t3

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [9]:
t4 = torch.tensor([1,2,3,4.])

In [10]:
t4

tensor([1., 2., 3., 4.])

In [11]:
t4.shape, t3.shape, t2.shape, t1.shape

(torch.Size([4]), torch.Size([2, 2, 3]), torch.Size([3, 2]), torch.Size([]))

In [12]:
# Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [13]:
y = w*x + b

In [14]:
y

tensor(17., grad_fn=<AddBackward0>)

In [15]:
y.backward()

In [16]:
# Display gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [17]:
import numpy as np
x = np.array([[1,2],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [18]:
# Convert numpy array to tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [19]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [20]:
# Convert torch tensor to numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])